plugins {
    id 'com.android.application'
}

android {
    namespace 'com.bsmith.customstopwatch'
    compileSdk 35

    defaultConfig {
        applicationId "com.bsmith.customstopwatch"
        minSdk 26
        targetSdk 35
        versionCode 3
        versionName "3.0"
    }

    signingConfigs {
        release {
            def signingKeyPath = System.getenv("ANDROID_KEYSTORE_FILE")
            if (signingKeyPath != null && !signingKeyPath.isEmpty()) {
                storeFile file(signingKeyPath)
                storePassword System.getenv("ANDROID_KEYSTORE_PASSWORD")
                keyAlias System.getenv("ANDROID_KEY_ALIAS")
                keyPassword System.getenv("ANDROID_KEY_PASSWORD")
            }
        }
    }

    buildTypes {
        release {
            def signingKeyPath = System.getenv("ANDROID_KEYSTORE_FILE")
            if (signingKeyPath != null && !signingKeyPath.isEmpty()) {
                signingConfig signingConfigs.release
            }
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}
